version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: my_mongodb_container
    ports:
      - "27017:27017"
    environment:
      MONGO_DB: ${MONGO_DB}
      MONGO_USER: ${MONGO_USER}
      MONGO_PASSWORD: ${MONGO_PASSWORD}